services:
  p4bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: p4bot:dev
    volumes:
      - ./app:/srv/p4bot/app:cached
      - ./secrets/p4tickets:/root/.p4tickets:ro
      - ./secrets/p4config:/root/.p4config:ro
      - ${SSH_AUTH_SOCK:-/ssh-auth-not-set}:/ssh-agent:ro
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - SSH_AUTH_SOCK=/ssh-agent
      - P4TICKETS=/root/.p4tickets
      - P4CONFIG=/root/.p4config
    command: ["gunicorn", "--reload", "-b", "0.0.0.0:8080", "app.server:app"]
    tty: true
