services:
  p4bot:
    build: .
    image: local/p4bot:latest
    ports:
      - "8080:8080"
    environment:
      - SLACK_COMMAND_MAP={}
    volumes:
      - ../:/srv/p4bot:cached
    restart: unless-stopped
    command: ["gunicorn", "-b", "0.0.0.0:8080", "app.server:app"]
