services:
  p4bot:
    build: .
    image: local/p4bot:latest
    ports:
      - "8080:8080"
    environment:
      - SLACK_COMMAND_MAP={}
      - P4PORT=ssl:mss-perforce-01.rit.edu:1666
      - P4USER=p4status
      - P4CLIENT=
    volumes:
      - ../:/srv/p4bot:cached
      - ./app:/srv/p4bot/app:cached
    restart: unless-stopped
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
